-- ====================================================================
-- VIDARIX - INITIAL SCHEMA MIGRATION FOR SUPABASE
-- Tables, Triggers, Functions, RLS Policies, and Storage Bucket
-- ====================================================================

-- 1. EXTENSIONS & SETUP
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to handle updated_at timestamps
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. TABLES CREATION

-- 2.1 PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  display_name TEXT,
  username TEXT,
  bio TEXT,
  avatar_url TEXT,
  avatar_path TEXT,
  country TEXT DEFAULT 'BR',
  language TEXT DEFAULT 'pt-BR',
  birth_date DATE,
  media_preference TEXT DEFAULT 'both',
  minimum_rating NUMERIC DEFAULT 0,
  maximum_runtime INTEGER,
  public_profile BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Case-insensitive unique index on username
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_username_lower ON public.profiles (LOWER(username));

-- 2.2 USER STREAMING PROVIDERS
CREATE TABLE IF NOT EXISTS public.user_streaming_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider_id INTEGER NOT NULL,
  provider_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, provider_id)
);

-- 2.3 USER FAVORITE GENRES
CREATE TABLE IF NOT EXISTS public.user_favorite_genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  genre_id INTEGER NOT NULL,
  genre_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, genre_id)
);

-- 2.4 USER EXCLUDED GENRES
CREATE TABLE IF NOT EXISTS public.user_excluded_genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  genre_id INTEGER NOT NULL,
  genre_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, genre_id)
);

-- 2.5 WATCHLIST
CREATE TABLE IF NOT EXISTS public.watchlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT NOT NULL,
  poster_path TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, tmdb_id, media_type)
);

-- 2.6 WATCHED TITLES
CREATE TABLE IF NOT EXISTS public.watched_titles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT NOT NULL,
  poster_path TEXT,
  watched_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, tmdb_id, media_type)
);

-- 2.7 FAVORITES
CREATE TABLE IF NOT EXISTS public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT NOT NULL,
  poster_path TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, tmdb_id, media_type)
);

-- 2.8 ROULETTE HISTORY
CREATE TABLE IF NOT EXISTS public.roulette_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT NOT NULL,
  poster_path TEXT,
  selection_mode TEXT,
  filters JSONB DEFAULT '{}'::jsonb,
  spun_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.9 USER RATINGS
CREATE TABLE IF NOT EXISTS public.user_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT NOT NULL,
  rating NUMERIC NOT NULL CHECK (rating >= 0 AND rating <= 10),
  review TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, tmdb_id, media_type)
);

-- 2.10 USER PREFERENCES
CREATE TABLE IF NOT EXISTS public.user_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  only_my_providers BOOLEAN DEFAULT TRUE,
  exclude_watched BOOLEAN DEFAULT TRUE,
  avoid_recent_results BOOLEAN DEFAULT TRUE,
  allow_surprises BOOLEAN DEFAULT TRUE,
  sound_enabled BOOLEAN DEFAULT TRUE,
  confetti_enabled BOOLEAN DEFAULT TRUE,
  animations_enabled BOOLEAN DEFAULT TRUE,
  autoplay_trailers BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TRIGGERS FOR UPDATED_AT
DROP TRIGGER IF EXISTS set_profiles_updated_at ON public.profiles;
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_user_ratings_updated_at ON public.user_ratings;
CREATE TRIGGER set_user_ratings_updated_at
  BEFORE UPDATE ON public.user_ratings
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_user_preferences_updated_at ON public.user_preferences;
CREATE TRIGGER set_user_preferences_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 4. AUTOMATIC PROFILE CREATION TRIGGER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  raw_user_name TEXT;
  clean_username TEXT;
BEGIN
  raw_user_name := COALESCE(
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'name',
    SPLIT_PART(NEW.email, '@', 1),
    'Cinéfilo VIDARIX'
  );

  clean_username := COALESCE(
    NEW.raw_user_meta_data->>'username',
    LOWER(REGEXP_REPLACE(SPLIT_PART(NEW.email, '@', 1), '[^a-zA-Z0-9._]', '', 'g'))
  );

  IF clean_username = '' OR clean_username IS NULL THEN
    clean_username := 'user_' || SUBSTRING(NEW.id::text FROM 1 FOR 8);
  END IF;

  INSERT INTO public.profiles (
    id,
    full_name,
    display_name,
    username,
    avatar_url,
    country,
    language,
    created_at,
    updated_at
  )
  VALUES (
    NEW.id,
    raw_user_name,
    COALESCE(NEW.raw_user_meta_data->>'display_name', SPLIT_PART(raw_user_name, ' ', 1), raw_user_name),
    clean_username,
    NEW.raw_user_meta_data->>'avatar_url',
    'BR',
    'pt-BR',
    NOW(),
    NOW()
  )
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_preferences (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. ROW LEVEL SECURITY (RLS) POLICIES

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaming_providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_favorite_genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_excluded_genres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watched_titles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roulette_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

-- 5.1 PROFILES POLICIES
DROP POLICY IF EXISTS "Profiles read policy" ON public.profiles;
CREATE POLICY "Profiles read policy" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public_profile = TRUE);

DROP POLICY IF EXISTS "Profiles insert policy" ON public.profiles;
CREATE POLICY "Profiles insert policy" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Profiles update policy" ON public.profiles;
CREATE POLICY "Profiles update policy" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Profiles delete policy" ON public.profiles;
CREATE POLICY "Profiles delete policy" ON public.profiles
  FOR DELETE USING (auth.uid() = id);

-- Helper macro function for user_id owned tables
-- 5.2 USER_STREAMING_PROVIDERS
DROP POLICY IF EXISTS "User providers select" ON public.user_streaming_providers;
CREATE POLICY "User providers select" ON public.user_streaming_providers FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "User providers insert" ON public.user_streaming_providers;
CREATE POLICY "User providers insert" ON public.user_streaming_providers FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "User providers update" ON public.user_streaming_providers;
CREATE POLICY "User providers update" ON public.user_streaming_providers FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "User providers delete" ON public.user_streaming_providers;
CREATE POLICY "User providers delete" ON public.user_streaming_providers FOR DELETE USING (auth.uid() = user_id);

-- 5.3 USER_FAVORITE_GENRES
DROP POLICY IF EXISTS "Fav genres select" ON public.user_favorite_genres;
CREATE POLICY "Fav genres select" ON public.user_favorite_genres FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Fav genres insert" ON public.user_favorite_genres;
CREATE POLICY "Fav genres insert" ON public.user_favorite_genres FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Fav genres update" ON public.user_favorite_genres;
CREATE POLICY "Fav genres update" ON public.user_favorite_genres FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Fav genres delete" ON public.user_favorite_genres;
CREATE POLICY "Fav genres delete" ON public.user_favorite_genres FOR DELETE USING (auth.uid() = user_id);

-- 5.4 USER_EXCLUDED_GENRES
DROP POLICY IF EXISTS "Excluded genres select" ON public.user_excluded_genres;
CREATE POLICY "Excluded genres select" ON public.user_excluded_genres FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Excluded genres insert" ON public.user_excluded_genres;
CREATE POLICY "Excluded genres insert" ON public.user_excluded_genres FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Excluded genres update" ON public.user_excluded_genres;
CREATE POLICY "Excluded genres update" ON public.user_excluded_genres FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Excluded genres delete" ON public.user_excluded_genres;
CREATE POLICY "Excluded genres delete" ON public.user_excluded_genres FOR DELETE USING (auth.uid() = user_id);

-- 5.5 WATCHLIST
DROP POLICY IF EXISTS "Watchlist select" ON public.watchlist;
CREATE POLICY "Watchlist select" ON public.watchlist FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watchlist insert" ON public.watchlist;
CREATE POLICY "Watchlist insert" ON public.watchlist FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watchlist update" ON public.watchlist;
CREATE POLICY "Watchlist update" ON public.watchlist FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watchlist delete" ON public.watchlist;
CREATE POLICY "Watchlist delete" ON public.watchlist FOR DELETE USING (auth.uid() = user_id);

-- 5.6 WATCHED_TITLES
DROP POLICY IF EXISTS "Watched select" ON public.watched_titles;
CREATE POLICY "Watched select" ON public.watched_titles FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watched insert" ON public.watched_titles;
CREATE POLICY "Watched insert" ON public.watched_titles FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watched update" ON public.watched_titles;
CREATE POLICY "Watched update" ON public.watched_titles FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Watched delete" ON public.watched_titles;
CREATE POLICY "Watched delete" ON public.watched_titles FOR DELETE USING (auth.uid() = user_id);

-- 5.7 FAVORITES
DROP POLICY IF EXISTS "Favorites select" ON public.favorites;
CREATE POLICY "Favorites select" ON public.favorites FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Favorites insert" ON public.favorites;
CREATE POLICY "Favorites insert" ON public.favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Favorites update" ON public.favorites;
CREATE POLICY "Favorites update" ON public.favorites FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Favorites delete" ON public.favorites;
CREATE POLICY "Favorites delete" ON public.favorites FOR DELETE USING (auth.uid() = user_id);

-- 5.8 ROULETTE_HISTORY
DROP POLICY IF EXISTS "History select" ON public.roulette_history;
CREATE POLICY "History select" ON public.roulette_history FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "History insert" ON public.roulette_history;
CREATE POLICY "History insert" ON public.roulette_history FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "History update" ON public.roulette_history;
CREATE POLICY "History update" ON public.roulette_history FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "History delete" ON public.roulette_history;
CREATE POLICY "History delete" ON public.roulette_history FOR DELETE USING (auth.uid() = user_id);

-- 5.9 USER_RATINGS
DROP POLICY IF EXISTS "Ratings select" ON public.user_ratings;
CREATE POLICY "Ratings select" ON public.user_ratings FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Ratings insert" ON public.user_ratings;
CREATE POLICY "Ratings insert" ON public.user_ratings FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Ratings update" ON public.user_ratings;
CREATE POLICY "Ratings update" ON public.user_ratings FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Ratings delete" ON public.user_ratings;
CREATE POLICY "Ratings delete" ON public.user_ratings FOR DELETE USING (auth.uid() = user_id);

-- 5.10 USER_PREFERENCES
DROP POLICY IF EXISTS "Preferences select" ON public.user_preferences;
CREATE POLICY "Preferences select" ON public.user_preferences FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Preferences insert" ON public.user_preferences;
CREATE POLICY "Preferences insert" ON public.user_preferences FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Preferences update" ON public.user_preferences;
CREATE POLICY "Preferences update" ON public.user_preferences FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Preferences delete" ON public.user_preferences;
CREATE POLICY "Preferences delete" ON public.user_preferences FOR DELETE USING (auth.uid() = user_id);

-- 6. STORAGE BUCKET & STORAGE POLICIES FOR AVATARS

-- Create 'avatars' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  TRUE,
  5242880, -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = TRUE,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp'];

-- Storage Objects Policies
DROP POLICY IF EXISTS "Public read access for avatars" ON storage.objects;
CREATE POLICY "Public read access for avatars" ON storage.objects
  FOR SELECT USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Authenticated user insert avatar" ON storage.objects;
CREATE POLICY "Authenticated user insert avatar" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'avatars' AND
    auth.role() = 'authenticated' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "Authenticated user update avatar" ON storage.objects;
CREATE POLICY "Authenticated user update avatar" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'avatars' AND
    auth.role() = 'authenticated' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "Authenticated user delete avatar" ON storage.objects;
CREATE POLICY "Authenticated user delete avatar" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'avatars' AND
    auth.role() = 'authenticated' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );
